drop table if exists supplier_order;

create table supplier_order(
    id integer primary key generated by default as identity,
    order_date Date default now(),
    item integer REFERENCES item(id) on DELETE CASCADE not null,
    amount numeric,
    total_cost numeric,
    shipping_status text
);